# Generated by Django 4.2.5 on 2024-03-29 22:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0003_pregunta_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='fecha_consulta',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
